---
- hosts: all
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World

    - name: Install httpd 
      yum:
        name: httpd
        state: latest
      become: true

    - name: Start Httpd Service
      service:
        name: httpd
        state: started
      become: true